/*
MIT License

Copyright (c) 2018 PodKubervisor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/amadeusitgroup/podkubervisor/pkg/api/kubervisor/v1"
	scheme "github.com/amadeusitgroup/podkubervisor/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BreakerConfigsGetter has a method to return a BreakerConfigInterface.
// A group's client should implement this interface.
type BreakerConfigsGetter interface {
	BreakerConfigs(namespace string) BreakerConfigInterface
}

// BreakerConfigInterface has methods to work with BreakerConfig resources.
type BreakerConfigInterface interface {
	Create(*v1.BreakerConfig) (*v1.BreakerConfig, error)
	Update(*v1.BreakerConfig) (*v1.BreakerConfig, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.BreakerConfig, error)
	List(opts meta_v1.ListOptions) (*v1.BreakerConfigList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.BreakerConfig, err error)
	BreakerConfigExpansion
}

// breakerConfigs implements BreakerConfigInterface
type breakerConfigs struct {
	client rest.Interface
	ns     string
}

// newBreakerConfigs returns a BreakerConfigs
func newBreakerConfigs(c *BreakerV1Client, namespace string) *breakerConfigs {
	return &breakerConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the breakerConfig, and returns the corresponding breakerConfig object, and an error if there is any.
func (c *breakerConfigs) Get(name string, options meta_v1.GetOptions) (result *v1.BreakerConfig, err error) {
	result = &v1.BreakerConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("breakerconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BreakerConfigs that match those selectors.
func (c *breakerConfigs) List(opts meta_v1.ListOptions) (result *v1.BreakerConfigList, err error) {
	result = &v1.BreakerConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("breakerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested breakerConfigs.
func (c *breakerConfigs) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("breakerconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a breakerConfig and creates it.  Returns the server's representation of the breakerConfig, and an error, if there is any.
func (c *breakerConfigs) Create(breakerConfig *v1.BreakerConfig) (result *v1.BreakerConfig, err error) {
	result = &v1.BreakerConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("breakerconfigs").
		Body(breakerConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a breakerConfig and updates it. Returns the server's representation of the breakerConfig, and an error, if there is any.
func (c *breakerConfigs) Update(breakerConfig *v1.BreakerConfig) (result *v1.BreakerConfig, err error) {
	result = &v1.BreakerConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("breakerconfigs").
		Name(breakerConfig.Name).
		Body(breakerConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the breakerConfig and deletes it. Returns an error if one occurs.
func (c *breakerConfigs) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("breakerconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *breakerConfigs) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("breakerconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched breakerConfig.
func (c *breakerConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.BreakerConfig, err error) {
	result = &v1.BreakerConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("breakerconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
