{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pricer.globalservice" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "pricer.name" . }}
    chart: {{ template "pricer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ $fullName }}.{{ .Values.ingress.domaine }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}