// +build !ignore_autogenerated

/*
MIT License

Copyright (c) 2018 PodKubervisor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakerConfig) DeepCopyInto(out *BreakerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakerConfig.
func (in *BreakerConfig) DeepCopy() *BreakerConfig {
	if in == nil {
		return nil
	}
	out := new(BreakerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakerConfigList) DeepCopyInto(out *BreakerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BreakerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakerConfigList.
func (in *BreakerConfigList) DeepCopy() *BreakerConfigList {
	if in == nil {
		return nil
	}
	out := new(BreakerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakerConfigSpec) DeepCopyInto(out *BreakerConfigSpec) {
	*out = *in
	in.Breaker.DeepCopyInto(&out.Breaker)
	out.Retry = in.Retry
	if in.Selector == nil {
		out.Selector = nil
	} else {
		out.Selector = in.Selector.DeepCopySelector()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakerConfigSpec.
func (in *BreakerConfigSpec) DeepCopy() *BreakerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BreakerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakerConfigStatus) DeepCopyInto(out *BreakerConfigStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakerConfigStatus.
func (in *BreakerConfigStatus) DeepCopy() *BreakerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BreakerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakerStrategy) DeepCopyInto(out *BreakerStrategy) {
	*out = *in
	if in.MinPodsAvailableCount != nil {
		in, out := &in.MinPodsAvailableCount, &out.MinPodsAvailableCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	if in.MinPodsAvailableRatio != nil {
		in, out := &in.MinPodsAvailableRatio, &out.MinPodsAvailableRatio
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	if in.DiscreteValueOutOfList != nil {
		in, out := &in.DiscreteValueOutOfList, &out.DiscreteValueOutOfList
		if *in == nil {
			*out = nil
		} else {
			*out = new(DiscreteValueOutOfList)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakerStrategy.
func (in *BreakerStrategy) DeepCopy() *BreakerStrategy {
	if in == nil {
		return nil
	}
	out := new(BreakerStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscreteValueOutOfList) DeepCopyInto(out *DiscreteValueOutOfList) {
	*out = *in
	if in.GoodValues != nil {
		in, out := &in.GoodValues, &out.GoodValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BadValues != nil {
		in, out := &in.BadValues, &out.BadValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TolerancePercent != nil {
		in, out := &in.TolerancePercent, &out.TolerancePercent
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	if in.MinimumActivityCount != nil {
		in, out := &in.MinimumActivityCount, &out.MinimumActivityCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscreteValueOutOfList.
func (in *DiscreteValueOutOfList) DeepCopy() *DiscreteValueOutOfList {
	if in == nil {
		return nil
	}
	out := new(DiscreteValueOutOfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryStrategy) DeepCopyInto(out *RetryStrategy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryStrategy.
func (in *RetryStrategy) DeepCopy() *RetryStrategy {
	if in == nil {
		return nil
	}
	out := new(RetryStrategy)
	in.DeepCopyInto(out)
	return out
}
