// +build !ignore_autogenerated

/*
MIT License

Copyright (c) 2018 Kubervisor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActivatorStrategy) DeepCopyInto(out *ActivatorStrategy) {
	*out = *in
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		if *in == nil {
			*out = nil
		} else {
			*out = new(float64)
			**out = **in
		}
	}
	if in.MaxRetryCount != nil {
		in, out := &in.MaxRetryCount, &out.MaxRetryCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	if in.MaxPauseCount != nil {
		in, out := &in.MaxPauseCount, &out.MaxPauseCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActivatorStrategy.
func (in *ActivatorStrategy) DeepCopy() *ActivatorStrategy {
	if in == nil {
		return nil
	}
	out := new(ActivatorStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakerStrategy) DeepCopyInto(out *BreakerStrategy) {
	*out = *in
	if in.EvaluationPeriod != nil {
		in, out := &in.EvaluationPeriod, &out.EvaluationPeriod
		if *in == nil {
			*out = nil
		} else {
			*out = new(float64)
			**out = **in
		}
	}
	if in.MinPodsAvailableCount != nil {
		in, out := &in.MinPodsAvailableCount, &out.MinPodsAvailableCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	if in.MinPodsAvailableRatio != nil {
		in, out := &in.MinPodsAvailableRatio, &out.MinPodsAvailableRatio
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	if in.DiscreteValueOutOfList != nil {
		in, out := &in.DiscreteValueOutOfList, &out.DiscreteValueOutOfList
		if *in == nil {
			*out = nil
		} else {
			*out = new(DiscreteValueOutOfList)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.ContinuousValueDeviation != nil {
		in, out := &in.ContinuousValueDeviation, &out.ContinuousValueDeviation
		if *in == nil {
			*out = nil
		} else {
			*out = new(ContinuousValueDeviation)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Activator != nil {
		in, out := &in.Activator, &out.Activator
		if *in == nil {
			*out = nil
		} else {
			*out = new(ActivatorStrategy)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakerStrategy.
func (in *BreakerStrategy) DeepCopy() *BreakerStrategy {
	if in == nil {
		return nil
	}
	out := new(BreakerStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContinuousValueDeviation) DeepCopyInto(out *ContinuousValueDeviation) {
	*out = *in
	if in.MaxDeviationPercent != nil {
		in, out := &in.MaxDeviationPercent, &out.MaxDeviationPercent
		if *in == nil {
			*out = nil
		} else {
			*out = new(float64)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContinuousValueDeviation.
func (in *ContinuousValueDeviation) DeepCopy() *ContinuousValueDeviation {
	if in == nil {
		return nil
	}
	out := new(ContinuousValueDeviation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscreteValueOutOfList) DeepCopyInto(out *DiscreteValueOutOfList) {
	*out = *in
	if in.GoodValues != nil {
		in, out := &in.GoodValues, &out.GoodValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BadValues != nil {
		in, out := &in.BadValues, &out.BadValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TolerancePercent != nil {
		in, out := &in.TolerancePercent, &out.TolerancePercent
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	if in.MinimumActivityCount != nil {
		in, out := &in.MinimumActivityCount, &out.MinimumActivityCount
		if *in == nil {
			*out = nil
		} else {
			*out = new(uint)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscreteValueOutOfList.
func (in *DiscreteValueOutOfList) DeepCopy() *DiscreteValueOutOfList {
	if in == nil {
		return nil
	}
	out := new(DiscreteValueOutOfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubervisorService) DeepCopyInto(out *KubervisorService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubervisorService.
func (in *KubervisorService) DeepCopy() *KubervisorService {
	if in == nil {
		return nil
	}
	out := new(KubervisorService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubervisorService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubervisorServiceCondition) DeepCopyInto(out *KubervisorServiceCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubervisorServiceCondition.
func (in *KubervisorServiceCondition) DeepCopy() *KubervisorServiceCondition {
	if in == nil {
		return nil
	}
	out := new(KubervisorServiceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubervisorServiceList) DeepCopyInto(out *KubervisorServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubervisorService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubervisorServiceList.
func (in *KubervisorServiceList) DeepCopy() *KubervisorServiceList {
	if in == nil {
		return nil
	}
	out := new(KubervisorServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubervisorServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubervisorServiceSpec) DeepCopyInto(out *KubervisorServiceSpec) {
	*out = *in
	if in.Breakers != nil {
		in, out := &in.Breakers, &out.Breakers
		*out = make([]BreakerStrategy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.DefaultActivator.DeepCopyInto(&out.DefaultActivator)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubervisorServiceSpec.
func (in *KubervisorServiceSpec) DeepCopy() *KubervisorServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KubervisorServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubervisorServiceStatus) DeepCopyInto(out *KubervisorServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]KubervisorServiceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		if *in == nil {
			*out = nil
		} else {
			*out = (*in).DeepCopy()
		}
	}
	if in.PodCounts != nil {
		in, out := &in.PodCounts, &out.PodCounts
		if *in == nil {
			*out = nil
		} else {
			*out = new(PodCountStatus)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubervisorServiceStatus.
func (in *KubervisorServiceStatus) DeepCopy() *KubervisorServiceStatus {
	if in == nil {
		return nil
	}
	out := new(KubervisorServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodCountStatus) DeepCopyInto(out *PodCountStatus) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodCountStatus.
func (in *PodCountStatus) DeepCopy() *PodCountStatus {
	if in == nil {
		return nil
	}
	out := new(PodCountStatus)
	in.DeepCopyInto(out)
	return out
}
