/*
MIT License

Copyright (c) 2018 PodKubervisor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kubervisor_v1 "github.com/amadeusitgroup/podkubervisor/pkg/api/kubervisor/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBreakerConfigs implements BreakerConfigInterface
type FakeBreakerConfigs struct {
	Fake *FakeBreakerV1
	ns   string
}

var breakerconfigsResource = schema.GroupVersionResource{Group: "breaker.kubervisor.io", Version: "v1", Resource: "breakerconfigs"}

var breakerconfigsKind = schema.GroupVersionKind{Group: "breaker.kubervisor.io", Version: "v1", Kind: "BreakerConfig"}

// Get takes name of the breakerConfig, and returns the corresponding breakerConfig object, and an error if there is any.
func (c *FakeBreakerConfigs) Get(name string, options v1.GetOptions) (result *kubervisor_v1.BreakerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(breakerconfigsResource, c.ns, name), &kubervisor_v1.BreakerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubervisor_v1.BreakerConfig), err
}

// List takes label and field selectors, and returns the list of BreakerConfigs that match those selectors.
func (c *FakeBreakerConfigs) List(opts v1.ListOptions) (result *kubervisor_v1.BreakerConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(breakerconfigsResource, breakerconfigsKind, c.ns, opts), &kubervisor_v1.BreakerConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kubervisor_v1.BreakerConfigList{}
	for _, item := range obj.(*kubervisor_v1.BreakerConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested breakerConfigs.
func (c *FakeBreakerConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(breakerconfigsResource, c.ns, opts))

}

// Create takes the representation of a breakerConfig and creates it.  Returns the server's representation of the breakerConfig, and an error, if there is any.
func (c *FakeBreakerConfigs) Create(breakerConfig *kubervisor_v1.BreakerConfig) (result *kubervisor_v1.BreakerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(breakerconfigsResource, c.ns, breakerConfig), &kubervisor_v1.BreakerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubervisor_v1.BreakerConfig), err
}

// Update takes the representation of a breakerConfig and updates it. Returns the server's representation of the breakerConfig, and an error, if there is any.
func (c *FakeBreakerConfigs) Update(breakerConfig *kubervisor_v1.BreakerConfig) (result *kubervisor_v1.BreakerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(breakerconfigsResource, c.ns, breakerConfig), &kubervisor_v1.BreakerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubervisor_v1.BreakerConfig), err
}

// Delete takes name of the breakerConfig and deletes it. Returns an error if one occurs.
func (c *FakeBreakerConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(breakerconfigsResource, c.ns, name), &kubervisor_v1.BreakerConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBreakerConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(breakerconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &kubervisor_v1.BreakerConfigList{})
	return err
}

// Patch applies the patch and returns the patched breakerConfig.
func (c *FakeBreakerConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *kubervisor_v1.BreakerConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(breakerconfigsResource, c.ns, name, data, subresources...), &kubervisor_v1.BreakerConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kubervisor_v1.BreakerConfig), err
}
