/*
MIT License

Copyright (c) 2018 PodKubervisor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by lister-gen. DO NOT EDIT.

// This file was automatically generated by lister-gen

package v1

import (
	v1 "github.com/amadeusitgroup/podkubervisor/pkg/api/kubervisor/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KubervisorServiceLister helps list KubervisorServices.
type KubervisorServiceLister interface {
	// List lists all KubervisorServices in the indexer.
	List(selector labels.Selector) (ret []*v1.KubervisorService, err error)
	// KubervisorServices returns an object that can list and get KubervisorServices.
	KubervisorServices(namespace string) KubervisorServiceNamespaceLister
	KubervisorServiceListerExpansion
}

// kubervisorServiceLister implements the KubervisorServiceLister interface.
type kubervisorServiceLister struct {
	indexer cache.Indexer
}

// NewKubervisorServiceLister returns a new KubervisorServiceLister.
func NewKubervisorServiceLister(indexer cache.Indexer) KubervisorServiceLister {
	return &kubervisorServiceLister{indexer: indexer}
}

// List lists all KubervisorServices in the indexer.
func (s *kubervisorServiceLister) List(selector labels.Selector) (ret []*v1.KubervisorService, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.KubervisorService))
	})
	return ret, err
}

// KubervisorServices returns an object that can list and get KubervisorServices.
func (s *kubervisorServiceLister) KubervisorServices(namespace string) KubervisorServiceNamespaceLister {
	return kubervisorServiceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KubervisorServiceNamespaceLister helps list and get KubervisorServices.
type KubervisorServiceNamespaceLister interface {
	// List lists all KubervisorServices in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.KubervisorService, err error)
	// Get retrieves the KubervisorService from the indexer for a given namespace and name.
	Get(name string) (*v1.KubervisorService, error)
	KubervisorServiceNamespaceListerExpansion
}

// kubervisorServiceNamespaceLister implements the KubervisorServiceNamespaceLister
// interface.
type kubervisorServiceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KubervisorServices in the indexer for a given namespace.
func (s kubervisorServiceNamespaceLister) List(selector labels.Selector) (ret []*v1.KubervisorService, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.KubervisorService))
	})
	return ret, err
}

// Get retrieves the KubervisorService from the indexer for a given namespace and name.
func (s kubervisorServiceNamespaceLister) Get(name string) (*v1.KubervisorService, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("kubervisorservice"), name)
	}
	return obj.(*v1.KubervisorService), nil
}
